[phases.setup]
nixPkgs = [
    "nodejs_22",
    "pnpm-9_x",
    "bash-completion",
    "vim",
    "less",
    "git",
    "htop",
    "tree",
    "jq",
    "ncdu",
    "ripgrep",
    "fzf",
    "fd"
]

[phases.install]
cmds = [
    "npm install -g corepack@0.24.1 && corepack enable",
    "pnpm i --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "sh -c 'echo \"source /etc/bash_completion\" >> ~/.bashrc && echo \"export TERM=xterm-256color\" >> ~/.bashrc && echo \"alias ls=\\\"ls --color=auto\\\"\" >> ~/.bashrc && echo \"PS1=\\\"\\\\[\\\\033[01;32m\\\\]\\\\u@\\\\h\\\\[\\\\033[00m\\\\]:\\\\[\\\\033[01;34m\\\\]\\\\w\\\\[\\\\033[00m\\\\]\\\\$ \\\"\" >> ~/.bashrc && if [ ! -f .env.local ] && [ ! -z \"$ANTHROPIC_API_KEY\" ]; then echo \"ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY\" > .env.local; fi && source ~/.bashrc && exec pnpm run start'"

[variables]
ANTHROPIC_API_KEY = "${ANTHROPIC_API_KEY}"
