[phases.setup]
nixPkgs = [
  "bash-completion",
  "less",
  "vim",
  "git",
  "htop",
  "tree",
  "jq"
]

[start]
cmd = "bash -c 'echo \"source /etc/bash_completion\" >> ~/.bashrc && echo \"alias ls=\\\"ls --color=auto\\\"\" >> ~/.bashrc && echo \"export PS1=\\\"\\[\\033[01;32m\\]\\u@\\h\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w\\[\\033[00m\\]\\$ \\\"\" >> ~/.bashrc && pnpm run start'"
